<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Estacionamento');
echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/estilo.css');
echo $this->doctype(); ?>

<!DOCTYPE html>
<html>
    <head>
        <title>Estacionamento</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>
        <div class="header">
			<img src="/images/logo.png"/>
            <?= "<h3>Estacionamento</h3>"; ?>
            <div class="topnav">
                <?= $this->navigation()->menu(); ?>
            </div>
            <div class="breadcrumbs">
                <?= $this->navigation()
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setLinkLast(true) 
                        ->setSeparator(" / ");
                        ?>
            </div>
        </div>
        <div class="content">
            <?= $this->layout()->content; ?>
        </div>
        <div class="bottom">
            <div>Layout padrão</div>
        </div>
    </body>
</html>
