<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Estacionamento');
echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css');
echo $this->doctype(); ?>

<!DOCTYPE html>
<html>
    <head>
        <title>Estacionamento</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <style>
            *{
                padding: 0 0; margin: 0 0;
                
            }
            div.topnav ul, .topnav ul li{
                display: inline;
                padding: 0px;
            }

            div.topnav ul li a{
                border-width: 1px 1px 0 1px;
                border-style: solid;
                border-color: #000;
                padding: 5px;
                background: #fff;
            }
            div.header{
                background: #eee;
                padding-bottom: 5px;
            }
            
            div.header > h3{
                margin-bottom: 10px;
                padding-top: 10px;
            }

            div.bottom {
                position: absolute;
                bottom: 0px;
                width: 100%;
                background: #ccc;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <?= "<h3>Estacionamento</h3>"; ?>
            <div class="topnav">
                <?= $this->navigation()->menu(); ?>
            </div>
            <div class="breadcrumbs">
                <?= $this->navigation()
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setLinkLast(true) 
                        ->setSeparator(" / ");
                        ?>
            </div>
        </div>
        <div class="content">
            <?= $this->layout()->content; ?>
        </div>
        <div class="bottom">
            <div>Layout padrão</div>
        </div>
    </body>
</html>
