<?php
$session = new Zend_Session_Namespace('session');
$this->headScript()->prependFile('/js/admin.js');
?>
<?php if (isset($session->str_id)) { ?>
    <div class="login">
        <a href="<?= $this->logout ?>">Sair</a>
    </div>
    <div class="card">
        <a href="<?= $this->gerir_card?>">Gerir Cartão</a>
    </div>
<?php } ?>
<div class="view_auth">
    <?= $this->auth ?>
</div>
<div class="logado_deslogado">
    <?= $this->str_log ?>
</div>
<div class="error_login">
    <?= $this->err_log ?>
</div>
<?php if (isset($session->str_id)) { ?>
    <div class="manager">
        <div class="functionality">
            <ul>
                <li  style="border: 1px solid #ccc"><?= $this->form_total_cartao ?></li>
                <li  style="border: 1px solid #ccc"><?= $this->form_tickets_pagos ?></li>
                <li  style="border: 1px solid #ccc"><?= $this->form_util_card_func ?></li>
            </ul>
        </div>
    </div>
<?php } ?>